using System.Collections;
using System;
using UnityEngine;

namespace QiQiuVert
{
  public interface ICharacterController
  {
    /// <summary>
    /// Returns the value of the navigation vector
    /// </summary>
    /// <returns>
    /// The orientation vector is generated by the input parameter
    /// </returns>

    public Vector3 UpdateAxis();

    /// <summary>
    /// Calculate and determine the rotation angle for object
    /// </summary>
    /// <returns>
    /// Angle with Degree Unit<br/>
    /// Item1 - Target angle follow object angle and camera angle<br/>
    /// Item2 - Angle object will rotate follow target angle<br/>
    /// </returns>

    public Tuple<float, float> GetRotationAngle();

    /// <summary>
    /// Move the object in the specified direction.
    /// </summary>
    /// <param name="direction">Vector specifies the direction of the object</param>

    public void Move(Vector3 direction);

  }
}
